[package]
name = "lifetime_func_sig_err"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name="no_lifetime"
path="src/no_lifetime.rs"

[[bin]]
name="longest_lifetime"
path="src/longest_lifetime.rs"
